services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./src/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./src/nginx/keys/:/etc/nginx/ssl/:ro
  webapp:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
    expose:
      - "8000"
